### Borrow Book
POST http://localhost:3000/borrowing
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "book_id": 3,
  "due_date": "2026-10-20"
}

### Return Book
GET   http://localhost:3000/borrowing/return/1
Authorization: Bearer TOKEN
